version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: baby_share_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BabyShare123
      POSTGRES_DB: baby_share
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - baby_share_network

  redis:
    image: redis:latest
    container_name: baby_share_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - baby_share_network

volumes:
  postgres_data:
  redis_data:

networks:
  baby_share_network:
    driver: bridge 