server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "BabyShare123"
  dbname: "baby_share"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

log:
  level: "debug"
  filename: "logs/app.log"
  maxsize: 100    # MB
  maxage: 7       # days
  maxbackups: 10  # 最多保留多少个备份
  compress: true  # 是否压缩 